name: Java build
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn -B -Dmaven.javadoc.skip=true compile
